"use server";

import { revalidatePath } from "next/cache";
import { supabaseAdmin as supabase } from "@/lib/api-keys";
import { requireAdmin } from "@/lib/authz";

export interface Project {
  id: string;
  title: string;
  slug: string;
  excerpt: string;
  content: string;
  status: "draft" | "published" | "archived";
  is_public: boolean;
  is_indexable: boolean;
  seo_title: string;
  seo_description: string;
  seo_keywords: string;
  featured_image_url: string;
  author_id: string;
  updated_at: string;
}

/**
 * Safe, user-facing error messages mapped from known Supabase error codes.
 * Prevents raw database error messages from leaking to the client (#18).
 */
const KNOWN_ERRORS: Record<string, string> = {
  "23505": "A project with this slug already exists. Choose a different slug.",
};

function sanitizeError(error: { code?: string; message: string }): string {
  if (error.code && KNOWN_ERRORS[error.code]) {
    return KNOWN_ERRORS[error.code];
  }
  return "Something went wrong. Please try again.";
}

// Type for updates that excludes immutable/autogenerated fields (#19)
export type ProjectUpdate = Omit<Project, "id" | "updated_at" | "author_id">;

export async function getProjects(): Promise<Project[]> {
  await requireAdmin();

  const { data, error } = await supabase
    .from("projects")
    .select("*")
    .order("updated_at", { ascending: false });

  if (error) throw new Error(sanitizeError(error));
  return data || [];
}

export async function getProject(id: string): Promise<Project | null> {
  await requireAdmin();

  const { data, error } = await supabase
    .from("projects")
    .select("*")
    .eq("id", id)
    .single();

  if (error) return null;
  return data;
}

export async function createProject(
  project: Omit<Project, "id" | "updated_at" | "author_id">
): Promise<Project> {
  const userId = await requireAdmin();

  const { data, error } = await supabase
    .from("projects")
    .insert({
      ...project,
      author_id: userId,
    })
    .select()
    .single();

  if (error) throw new Error(sanitizeError(error));
  revalidatePath("/dashboard/projects");
  return data;
}

export async function updateProject(
  id: string,
  updates: Partial<ProjectUpdate>
): Promise<Project> {
  await requireAdmin();

  // author_id is excluded from ProjectUpdate so it can't be changed (#19)
  const { data, error } = await supabase
    .from("projects")
    .update(updates)
    .eq("id", id)
    .select()
    .single();

  if (error) throw new Error(sanitizeError(error));
  revalidatePath("/dashboard/projects");
  return data;
}

export async function deleteProject(id: string): Promise<void> {
  await requireAdmin();

  const { error } = await supabase
    .from("projects")
    .delete()
    .eq("id", id);

  if (error) throw new Error(sanitizeError(error));
  revalidatePath("/dashboard/projects");
}
